name: "The United States Web Design System (USWDS) 2.0 Hugo Theme"
license: "CCO"
licenselink: "https://github.com/usnistgov/hugo-uswds/blob/master/LICENSE.md"
description: "A hugo theme based on the United States Web Design System (USWDS) 2.0"
homepage: "https://github.com/usnistgov/hugo-uswds"
tags:
features:
author:
  name: "David Waltermire"
  homepage: "https://www.nist.gov/people/david-waltermire"
original:
  name: "The United States Web Design System (USWDS) 2.0"
  homepage: "https://designsystem.digital.gov/"
  repo: "https://github.com/uswds/uswds"
module:
  hugoVersion:
    min: 0.111.0
    extended: true
  mounts:
  - source: dist/js
    target: static/module/hugo-uswds/js
  - source: dist/css
    target: static/module/hugo-uswds/css
  - source: dist/img
    target: static/module/hugo-uswds/img
  - source: dist/fonts
    target: static/module/hugo-uswds/fonts
  - source: layouts
    target: layouts
  - source: archetypes
    target: archetypes/module/hugo-uswds
